arm:
  joints:
    # Joint 0 (Shoulder Rotation)
    - limits: [-3.0542, 3.0542]
      motors:
        - id: 1
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 2048
          radsPerPos: 0.00153398193
    # Joint 1 (Shoulder Flexion)
    - limits: [-1.5708, 1.5708]
      motors:
        - id: 2
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 0 # This zero position will be homed
          radsPerPos: -0.000428088  
        - id: 3
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 0 # This zero position will be homed
          radsPerPos: 0.000428088
    # Joint 2 (Elbow Flexion)
    - limits: [-1.5708, 1.5708]
      motors:
        - id: 4
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 0 # This zero position will be homed
          radsPerPos: -0.000428088
        - id: 5
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 0 # This zero position will be homed
          radsPerPos: 0.000428088
    # Joint 3 (Forearm Rotation)
    - limits: [-3.0542, 3.0542]
      motors:
        - id: 6
          p: 3600
          i: 7000
          d: 2000
          ff2: 2000
          ff1: 3000
          zeroPos: 2048
          radsPerPos: 0.00153398193
    # Joint 4 (Wrist Flexion)
    - limits: [-2.0071, 1.7453]
      motors:
        - id: 7
          p: 3600
          i: 2000
          d: 2000
          ff2: 1000
          ff1: 2000
          zeroPos: 2048
          radsPerPos: -0.00153398193
    # Joint 5 (Wrist Rotation)
    - limits: [-3.0542, 3.0542]
      motors:
        - id: 8
          p: 3600
          i: 0
          d: 640
          ff2: 0
          ff1: 0
          zeroPos: 2048
          radsPerPos: 0.00153398193
  gripper:
    limits: [2600, 3900]
    motor:
      id: 9
      p: 3600
      i: 0
      d: 640
      ff2: 0
      ff1: 0
      #Gripper doesn't have angle control, so no angle data provided
      zeroPos: 0
      radsPerPos: 0
